/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-09-11 at 08:50:51 UTC 
 * Modify at your own risk.
 */

package com.born2go.lazzybee.gdatabase.server.dataServiceApi.model;

/**
 * Model definition for Voca.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the LazzyBee Backend Api. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Voca extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String a;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private Long gid;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String level;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String packages;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String q;

  /**
   * @return value or {@code null} for none
   */
  public String getA() {
    return a;
  }

  /**
   * @param a a or {@code null} for none
   */
  public Voca setA(String a) {
    this.a = a;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Long getGid() {
    return gid;
  }

  /**
   * @param gid gid or {@code null} for none
   */
  public Voca setGid(Long gid) {
    this.gid = gid;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getLevel() {
    return level;
  }

  /**
   * @param level level or {@code null} for none
   */
  public Voca setLevel(String level) {
    this.level = level;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getPackages() {
    return packages;
  }

  /**
   * @param packages packages or {@code null} for none
   */
  public Voca setPackages(String packages) {
    this.packages = packages;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getQ() {
    return q;
  }

  /**
   * @param q q or {@code null} for none
   */
  public Voca setQ(String q) {
    this.q = q;
    return this;
  }

  @Override
  public Voca set(String fieldName, Object value) {
    return (Voca) super.set(fieldName, value);
  }

  @Override
  public Voca clone() {
    return (Voca) super.clone();
  }

}
